bestand <- file("household_power_consumption.txt")
data <- read.table(text = grep("^[1,2]/2/2007", readLines(bestand), value = TRUE), col.names = c("Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_intensity", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), sep = ";", header = TRUE)
close(bestand)
data$DateTime <- strptime(paste(data$Date, data$Time),format = "%d/%m/%Y %H:%M:%S")
png(file="plot3.png",width = 480, height = 480)
plot(data$DateTime,data$Sub_metering_1, main="", xlab = "", ylab="Energy sub metering", type="l", col="black")
lines(data$DateTime,data$Sub_metering_2, type="l", col="red")
lines(data$DateTime,data$Sub_metering_3, type="l", col="blue")
legend(x="topright",y=NULL, legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col=c("black","red","blue"), lty=1)
dev.off()
